### ISSUE TITLE
Crashing when fetching > 800 contacts

### ISSUE THREAD

**Issue by homanp** [joshuapinter/react-native-unified-contacts#2]
Seems like the app is crashing due to memory when fetching > 800 contacts. Any idea on how to fix this?

/ Ismail

**Comment by joshuapinter** [comment]
I was able to fetch ~2500 contacts on my simulator and device. 

Are you fetching the phone numbers as well, via #1?

Also, do many of the contacts have thumbnails?

**Comment by homanp** [comment]
Yeah, with phone numbers. Not that many have thumbs. Could you run the simulator with my branch. To test with your 2500 contacts?

**Comment by joshuapinter** [comment]
You bet. I'll test it shortly.

If you don't return the phone numbers do you still hit a memory limit?

**Comment by homanp** [comment]
Don't know. A user that filed the bug. Tested to on 300 contacts only. I'm afk but will test when I get to my computer

**Comment by joshuapinter** [comment]
Tested on both master and your branch. They both work fine with ~2500 contacts. 

It might be what you're trying to do with the contacts after they are fetched.

Can you try and see if you can fetch the contacts okay without doing any manipulation afterwards?

**Comment by homanp** [comment]
Yeah, after fetching I just save it to my store in React. Really strange.

**Comment by homanp** [comment]
getPhoneContacts() {
    let self = this;
    PhoneContacts.requestAccessToContacts((userCanAccessContacts) => {
      if (userCanAccessContacts) {
        PhoneContacts.getContacts((err, contacts) =>  {
          if (err) return;
          ContactStore.setPhoneContacts(contacts);
        });
      }
      else {
        AlertIOS.alert(
          "Can't Access Your Contacts",
          "Click on Open Settings and allow ntwrk to access your Contacts.\n" +
          "\n" +
          "Then come back!",
          [
            {text: 'Open Settings', onPress: () => Contacts.openPrivacySettings() },
            {text: "Later"}
          ]
        )
      }
    });
  }

**Comment by joshuapinter** [comment]
Can you do a 'console.log(contacts)' right before 'if (err) return;' and see if your Chrome log shows the contact objects?

**Comment by homanp** [comment]
@joshuapinter How did you import 2500 contacts into the simulator?

I would like to do the same thing to check what's happening with the memory.

**Comment by joshuapinter** [comment]
@homanp Good question. By default it doesn't have very many. I ended up syncing my iCloud contacts into my simulator. 

This StackOverflow Answer is where I got the idea from: http://stackoverflow.com/a/32783266/293280

**Comment by homanp** [comment]
@joshuapinter cool. I added about 800 contacts and I'm getting this
<img width="1792" alt="screen shot 2016-05-05 at 23 06 38" src="https://cloud.githubusercontent.com/assets/2464556/15057386/cee5a3fa-1316-11e6-8f57-656a582780bc.png">

**Comment by homanp** [comment]
And the stacktrace

`libswiftCore.dylib`function signature specialization <Arg[0] = Exploded, Arg[1] = Exploded, Arg[2] = Dead, Arg[3] = Dead> of Swift._fatalErrorMessage (Swift.StaticString, Swift.StaticString, Swift.StaticString, Swift.UInt) -> ():
    0x107e73180 <+0>:   pushq  %rbp
    0x107e73181 <+1>:   movq   %rsp, %rbp
    0x107e73184 <+4>:   pushq  %rbx
    0x107e73185 <+5>:   pushq  %rax
    0x107e73186 <+6>:   movq   %rcx, %r10
    0x107e73189 <+9>:   testb  $0x1, %dl
    0x107e7318c <+12>:  jne    0x107e731aa               ; <+42>
    0x107e7318e <+14>:  testq  %rsi, %rsi
    0x107e73191 <+17>:  js     0x107e731f9               ; <+121>
    0x107e73193 <+19>:  addq   %rdi, %rsi
    0x107e73196 <+22>:  movzbl %r9b, %eax
    0x107e7319a <+26>:  movq   %r10, %rdx
    0x107e7319d <+29>:  movq   %r8, %rcx
    0x107e731a0 <+32>:  movl   %eax, %r8d
    0x107e731a3 <+35>:  callq  0x107eccea0               ; function signature specialization <Arg[0] = Exploded, Arg[1] = Exploded> of Swift.(_fatalErrorMessage (Swift.StaticString, Swift.StaticString, Swift.StaticString, Swift.UInt) -> ()).(closure #2)
->  0x107e731a8 <+40>:  ud2    
    0x107e731aa <+42>:  movq   $0x0, -0x10(%rbp)
    0x107e731b2 <+50>:  movl   %edi, %eax
    0x107e731b4 <+52>:  cmpq   %rax, %rdi
    0x107e731b7 <+55>:  jne    0x107e73303               ; <+387>
    0x107e731bd <+61>:  cmpl   $0xd7ff, %edi             ; imm = 0xD7FF 
    0x107e731c3 <+67>:  ja     0x107e73222               ; <+162>
    0x107e731c5 <+69>:  xorl   %esi, %esi
    0x107e731c7 <+71>:  cmpl   $0x80, %edi
    0x107e731cd <+77>:  movl   $0x0, %r11d
    0x107e731d3 <+83>:  jb     0x107e732f6               ; <+374>
    0x107e731d9 <+89>:  movl   %edi, %r11d
    0x107e731dc <+92>:  shrl   $0x6, %r11d
    0x107e731e0 <+96>:  cmpl   $0x800, %edi              ; imm = 0x800 
    0x107e731e6 <+102>: jae    0x107e7329b               ; <+283>
    0x107e731ec <+108>: orb    $-0x40, %r11b
    0x107e731f0 <+112>: xorl   %esi, %esi
    0x107e731f2 <+114>: xorl   %ebx, %ebx
    0x107e731f4 <+116>: jmp    0x107e732c6               ; <+326>
    0x107e731f9 <+121>: leaq   0xd3d92(%rip), %rdi       ; "fatal error"
    0x107e73200 <+128>: leaq   0xd3f89(%rip), %rcx       ; "UnsafeBufferPointer with negative count"
    0x107e73207 <+135>: movl   $0xb, %esi
    0x107e7320c <+140>: movl   $0x2, %edx
    0x107e73211 <+145>: movl   $0x27, %r8d
    0x107e73217 <+151>: movl   $0x2, %r9d
    0x107e7321d <+157>: callq  0x107e73180               ; <+0>
    0x107e73222 <+162>: cmpl   $0xe000, %edi             ; imm = 0xE000 
    0x107e73228 <+168>: jb     0x107e73272               ; <+242>
    0x107e7322a <+170>: cmpl   $0x110000, %edi           ; imm = 0x110000 
    0x107e73230 <+176>: jae    0x107e73352               ; <+466>`

**Comment by joshuapinter** [comment]
No idea. Can you do some more diagnostics:

1) Try commenting out the thumbnail image data stuff and see if it returns the contacts okay. 

2) Try limiting the number of contacts to see if that's an issue.

3) Try handling the error and setting a breakpoint to see if it's a particular contact's thumbnail that is causing the problem.

**Comment by homanp** [comment]
1) Commented out the thumbnail stuff and everything works fine.

2) Limiting number of contacts does not help

Will try to handle the error and see what I come up with.

**Comment by homanp** [comment]
@joshuapinter after examining the code I found out that `thumbnailImageData` can be nil even if 'imageDataAvailable' is `True`. I made a pull request for the fix. #3

**Comment by joshuapinter** [comment]
Good catch @homanp! I merged #3 so I'll close this Issue. 👍

**Comment by homanp** [comment]
@joshuapinter thanks, I filed a bug to iOS team as well.

**Comment by joshuapinter** [comment]
Perfect. Did you happen to test if the full image data was available when the thumbnail was nil but the imageDataAvailable was true?

On Fri, May 6, 2016 at 12:24 PM, Ismail Pelaseyed <notifications@github.com> wrote:
@joshuapinter [https://github.com/joshuapinter] thanks, I filed a bug to iOS team as well.

**Comment by homanp** [comment]
I did not test if imageData was present or not. That could've been the issue as well. I can test it and get back to you today

**Comment by joshuapinter** [comment]
Sounds good. Would be nice to know to further figure out the value of `imageDataAvailable`.
