### ISSUE TITLE
Is it safe to get 'countryCode' and 'digits' for phoneNumbers?

### ISSUE THREAD

**Issue by joonhocho** [joshuapinter/react-native-unified-contacts#20]
http://stackoverflow.com/questions/34730543/ios-9-get-cncontact-country-code-and-phone-number

@joshuapinter If you read the thread, some say Apple may reject an app that uses private apis.

**Comment by joshuapinter** [comment]
Interesting... I've been using it in **[ntwrk](http://ntwrkapp.com/)** for about 6 months without an issue.

Thoughts on closing this issue until an actual problem is reported?

**Comment by joonhocho** [comment]
@joshuapinter Agreed. Thanks!

**Comment by joshuapinter** [comment]
👍
