### ISSUE TITLE
getting error 'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by rishiankush** [joshuapinter/react-native-unified-contacts#22]
I am getting this error while installing this package.
![screen shot 2017-03-08 at 7 43 02 am](https://cloud.githubusercontent.com/assets/25289937/23687090/ec96b1ac-03d2-11e7-8bea-5aa48dd2a679.png)

**Comment by joshuapinter** [comment]
What React and React Native version are you on?

**Comment by rishiankush** [comment]
I am using React-15.4.1 and React-native 0.39.2

**Comment by joshuapinter** [comment]
Kay, can you replace that line with the following and tell me if it works? 

```objective-c
#if __has_include("RCTBridgeModule.h")
#import "RCTBridgeModule.h"
#else
#import <React/RCTBridgeModule.h>
#endif
```

**Comment by rishiankush** [comment]
perfect it worked! I think you should update this in your library so that there should not be any conflict in the syntax for new and old versions of react-native.

here is the screenshot:
![screen shot 2017-03-08 at 7 51 33 am](https://cloud.githubusercontent.com/assets/25289937/23687485/b3cd0522-03d4-11e7-8c15-48215b6d9c5d.png)

Thanks for your help!

**Comment by joshuapinter** [comment]
You bet I will. That was originally the plan - see #17 -  but the PR got closed and was never fixed again. 

Thanks for bringing this up again.

**Comment by joshuapinter** [comment]
Done! 👍
