### ISSUE TITLE
Use Legacy Swift Language Version

### ISSUE THREAD

**Issue by Dielz98** [joshuapinter/react-native-unified-contacts#31]
Hi I encounter build error

```
Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
```

Am I missing something?

**Comment by joshuapinter** [comment]
What XCode version are you running?

**Comment by Dielz98** [comment]
XCode 8.3 and iOS 10.2

**Comment by eugenehp** [comment]
@Dielz98 
Did you add `Contacts` and `ContactsUI` frameworks?
Do you have `SWIFT_VERSION` set in your `Build Settings`?

**Comment by joshuapinter** [comment]
I just updated this to use Swift 4 and it runs great in XCode 9.2. 

Closing this issue for now. 

Try out the latest version of the package, 1.6.1 and let me know how it goes. 

Thanks.
