### ISSUE TITLE
Swift Migration

### ISSUE THREAD

**Issue by elliotfleming** [joshuapinter/react-native-unified-contacts#35]
Please consider migrating this project to Swift 4 or at least 3.2...

I realize you aren't maintaining this project anymore but this is the ONLY React Native library that supports all the Contacts features and yet it's the only one that will not work with Xcode 9.2.

It would take a short time and have a big impact. Thank you!

**Comment by joshuapinter** [comment]
Hi @elliotfleming. I open it up in XCode 9.2 and got everything working with Swift 4.

I created an ExampleApp with the latest version of React Native (0.52.2) as well.

This was done #36.

I published a new version to npm, 1.6.1. 

**Can you try that out and let me know if everything is working for you?**

Make sure to test the ExampleApp, as per the [README Instructions](https://github.com/joshuapinter/react-native-unified-contacts#troubleshooting), if you run into trouble.

**Comment by elliotfleming** [comment]
Many many thanks! Working now!

**Comment by joshuapinter** [comment]
@elliotfleming Awesome! Thanks for following up!
