### ISSUE TITLE
Question: Possible to get the current user's contact?

### ISSUE THREAD

**Issue by paintedbicycle** [joshuapinter/react-native-unified-contacts#39]
Is there a method for getting the contact of the device's current user?

Paul

**Comment by joshuapinter** [comment]
Interesting. Never tried it. I'm pretty sure iOS/macOS automatically creates a Contact Card for the Operating System user so it should be in there. Just not sure if there is an easy way to find it or if you have to search by name, etc. like all the others.

**Comment by paintedbicycle** [comment]
I think on Android there is something called the "Me" card. And on iOS I know the system has the word "me" beside your contact if you're looking in the system Contacts app. But I'd love to be able to return this card.

See Android: https://github.com/rt2zz/react-native-contacts/pull/55

**Comment by joshuapinter** [comment]
Oh nice. That would be good. I'll keep this as an enhancement. PRs are always welcome! :)

**Comment by paintedbicycle** [comment]
I'm interested in helping out, but currently your Android support is stuck in a branch and your iOS add/update methods don't include postal addresses so I had to go with another library. If I switch my project over to yours I'll start contributing here what I can, though I'm not a Swift nor Java dev. Mostly I was just interested if you'd heard of it. It seems Android is possible but I haven't seen any info for iOS.

**Comment by paintedbicycle** [comment]
@joshuapinter Sent you a PR for iOS postal address updates. If we can get this merged I'll move my project over to your library.

**Comment by paintedbicycle** [comment]
After some research, it does not appear to be possible on iOS.

I'll close this for now as it would violate feature parity between iOS and Android.

Feel free to re-open if:
1. That is not a requirement for this feature
2. You want to create a UI workaround where the user is asked for this contact (from the contact picker) and once selected, it's remembered. I'll likely be doing this in my app, but I'm not sure it's a goal of this library.

**Comment by joshuapinter** [comment]
@paintedbicycle I concur. Handling this yourself is probably the best way to go, because you generally want to do other stuff with it, like attach it to the user's profile, etc.

Thanks for investigating and bringing this up.
