### ISSUE TITLE
Module RNUnifiedContacts requires main queue setup

### ISSUE THREAD

**Issue by piotrgorecki** [joshuapinter/react-native-unified-contacts#41]
Hi

I have got the following yellow box warning:

> Module RNUnifiedContacts requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

RN: 54.2
react-native-unified-contacts: 1.6.2

**Comment by paintedbicycle** [comment]
Hi @piotrgorecki can you try PR https://github.com/joshuapinter/react-native-unified-contacts/pull/45 and let me know if it fixes it?

Thanks

**Comment by paintedbicycle** [comment]
@joshuapinter I'd like to hear from @piotrgorecki on this one as I saw this error but it was elusive. I want to make sure I actually solved it. @piotrgorecki can you confirm? If you need me to dig deeper, let me know and I can try to recreate. I'm not super solid with Swift just yet and I have some doubts about the +'s in my PR. Over to you @piotrgorecki

**Comment by paintedbicycle** [comment]
Ok, I have re-confirmed this fix. We're good.

**Comment by joshuapinter** [comment]
@paintedbicycle Great job!

**Comment by piotrgorecki** [comment]
Hi @paintedbicycle ! I checked your fix and it works great. Thanks and I'm sorry for the late answer.

**Comment by bradennapier** [comment]
Any plans to implement this in the actual repo? I am getting this warning - just installed for my first time.

![image](https://user-images.githubusercontent.com/15365418/48242154-ba952d80-e38e-11e8-9ad1-34c9f1095a66.png)

**Comment by paintedbicycle** [comment]
It was fixed (as shown above), what version of the repo are you using?

You may have to use the bleeding edge:

```
package.json:

   "react-native-unified-contacts": "https://github.com/joshuapinter/react-native-unified-contacts.git",

```
