### ISSUE TITLE
[Android] Finalize checkPermissions

### ISSUE THREAD

**Issue by paintedbicycle** [joshuapinter/react-native-unified-contacts#53]
1. Android permissions check should check if multiple permissions have been granted (READ_CONTACTS, WRITE_CONTACTS and READ_PROFILE I believe are the ones). Right now Android does a basic check, but it would be smart to check multiple permissions in an array and return this to the developer in a smart way. Keep in mind we should try to match iOS functionality but on both platforms do it in a platform expected way.

2. A popup needs to be built to show the permissions request information as per best practices in permissionsAndroid at runtime. See ActivityCompat.shouldShowRequestPermissionRationale() and onRequestPermissionsResult()

An example here: https://www.sitepoint.com/requesting-runtime-permissions-in-android-m-and-n/

3. A developer could perhaps pass in what permissions they need in the app JS (READ, WRITE)

4. A developer should be able to pass in string for what message to show user in the popup

5. We need to handle what happens if you're already asked. A user on Android can say "never ask again" and this should match the iOS functionality where you can only ever ask once (effectively the same as saying "never ask again"). You can check for the on Android and devs should be able to check that and show different UI

**Comment by joshuapinter** [comment]
Reading Contacts is pretty much good to go, besides maybe allowing for custom text in the modal to show users and handling when a user checks the "don't ask again".

Still need to do Write and maybe the Profile one as well.

**Comment by paintedbicycle** [comment]
Cool!

I'm working through testing this. The new permissions seems to be mostly working, except right after requesting permissions for the first time I got this crash:

<img width="992" alt="screen shot 2018-05-12 at 9 59 57 pm" src="https://user-images.githubusercontent.com/371114/39961134-ee615694-562f-11e8-972c-638eb00c7c84.png">

So to summarize:

- 1. The "alreadyRequestedAccessToContacts" check in my app went fine and returned false showing the "request" button
- 2. Then I clicked a button to request access - the pop up appears fine
- 3. I click "Allow" on the pop up
- 4. App crashes

Paul

**Comment by joshuapinter** [comment]
Just pushed an update. Try with the lastest in `master`.

**Comment by paintedbicycle** [comment]
Hmm, now my app is back to crashing when interacting with the photo module.

<img width="979" alt="screen shot 2018-05-12 at 10 40 51 pm" src="https://user-images.githubusercontent.com/371114/39961406-8bd18d2c-5635-11e8-9ab8-dba803b7fa71.png">

**Comment by joshuapinter** [comment]
Hmm, and you're using this: `Contacts.requestAccessToContactsAsPromise`?

**Comment by paintedbicycle** [comment]
No I haven't moved to the promise version of anything. I need to keep parity between iOS and Android

**Comment by paintedbicycle** [comment]
It was working fine before that last change you did

**Comment by joshuapinter** [comment]
Okay, I'm going to remove the promise stuff for now. It's just causing confusion. We'll replace all the callbacks with Promises later, and do it with iOS so your app stays in parity for both platforms. 

Give me two seconds to push a new update.

**Comment by paintedbicycle** [comment]
Ok cool. I think the idea of moving to promises is great. But indeed, it'd have to be the same for both platforms.

**Comment by joshuapinter** [comment]
Okay, give that a whirl. And make sure to reload the Android Studio and to reload the react native bundle.

All Promises have been removed so there shouldn't be any confusion there and the errors shouldn't reference a Promise anywhere.

**Comment by paintedbicycle** [comment]
Note: Update below - found the source of the error.

Tested it out - it fixed the activity issue (crashing when interacting with the camera), but there is a weird bug with the permissions states. I have created a video and will describe the issue as well:

1. alreadyRequestedAccessToContacts works fine at first and correctly shows the my "Allow Access" button on a fresh app install
2. Clicking "Allow Access" in my app pops up the allow access modal from your library
3. Clicking "Allow" on that modal correctly switches the system permissions toggle granting my app contact access
4. The app does not understand it has access - in fact the app gets told it does NOT have access (this is the bug)
5. Then, interestingly, when running the app again, it does not remember that it has asked before, so I have to click my apps "allow" again - but this time the modal does not pop up (because it already has access at the system level)
6. My app then immediately shows my "denied" text.

So, it appears that the permissions is correctly interacting with the system, but perhaps this new preferences variable you're setting is acting strangely?

Full video below should make it clear. I show at each step what the system setting shows and what my app shows, including when going through the app a second time: https://paintedbicycle.com/permissions-issue.mp4


** UPDATE **

Ok - I looked into it more and realized that your API is different between iOS and Android. Not the method names, but the return values.

In Android:
Contacts.requestAccessToContacts( ( errors, canUserAccessContacts ) => {}

In iOS (and what is documented in ReadMe):
Contacts.requestAccessToContacts( (canUserAccessContacts ) => {}

So this is causing the above error. And if I run your current exampleApp in iOS, it crashes.

**Comment by joshuapinter** [comment]
Haha. No, definitely not annoying. This is super useful and very much appreciated. You are a collaborator after all so it feels like we're working through these together. :)

Now, on to issue. Yup, you're totally right. I don't know why I used different callback returns for different methods. Makes no sense to me. I'll update Android to match the existing documentation and iOS. 

Another nice thing about using Promises later is that it will eliminate this potential confusion and simplify things. 

Give me a minute and I'll push a new commit.

**Comment by joshuapinter** [comment]
Okay, pushed a new update that should fix that. I made the callbacks match the README. The fact that some return `( errors, result )` and some return just `( result )` is mind-boggling dumb. Shame on my past self for doing that. 🙈 

Give it a try when you can and confirm it's all good.

**Comment by paintedbicycle** [comment]
Yep, permissions seem good to go!

**Comment by joshuapinter** [comment]
👍 Should we close this or leave it open for writing contacts, etc.?

**Comment by paintedbicycle** [comment]
Let's close it, as Android doesn't currently allow writing. We can increase permissions as part of that ticket

**Comment by joshuapinter** [comment]
💯 👍
