### ISSUE TITLE
[Android Branch] Update readme to show status of iOS/Android methods support

### ISSUE THREAD

**Issue by paintedbicycle** [joshuapinter/react-native-unified-contacts#61]
We need a simple support table like this one: https://github.com/rt2zz/react-native-contacts#status that shows each of the methods available to a developer and their status on both iOS and Android

**Comment by joshuapinter** [comment]
Great idea! Did this in a5a2c57e6df7e5e2707d0df454e96b7d6ba69f06. Having the green checks and red crosses looks great and gives us something to work towards:

<img width="570" alt="screenshot 2018-05-09 22 11 18" src="https://user-images.githubusercontent.com/180819/39851732-ead29a9e-53d5-11e8-98a0-16fd9ed63635.png">
