### ISSUE TITLE
Bump npm version

### ISSUE THREAD

**Issue by paintedbicycle** [joshuapinter/react-native-unified-contacts#64]
We've made some feature updates to the master branch including adding the ability to save postal addresses. 

We should have someone other than me who added the code do a thorough test and then bump the npm version so people using the library can be notified and start using the feature.

**Comment by joshuapinter** [comment]
I'm going to close this because there likely won't be a package bump until Version 2.0 is released with full Android support and Promises instead of Callbacks. And then after that we'll keep the npm package as updated as possible.
