### ISSUE TITLE
Cant Find Variable contactData

### ISSUE THREAD

**Issue by rajanrai93** [joshuapinter/react-native-unified-contacts#66]
Hey Joshua. every time i run the function to add a contact it throws an error at me saying it can't find the variable "contactData". Am I placing the variable in the wrong location?
Thank you 
Rajan

<img width="712" alt="screen shot 2018-04-24 at 3 09 28 am" src="https://user-images.githubusercontent.com/22645756/39180899-f35b1b8e-476c-11e8-89a0-0a259b2acdb5.png">

**Comment by joshuapinter** [comment]
Try placing your `let contactData` declaration inside of your `_addContact()` function.
