### ISSUE TITLE
Installation instructions help

### ISSUE THREAD

**Issue by rgovindji** [joshuapinter/react-native-unified-contacts#7]
I added the RNUnifiedContacts folder to the root of my project as described in the instructions but when I try to do var Contacts = require('react-native-unified-contacts'); I get an undefined object. Do I need to do anything else aside from adding the folder? Also could you add rnpm integration to make this process easier?

**Comment by joshuapinter** [comment]
Did you install the npm package and follow the rest of the installation instructions?

**Comment by rgovindji** [comment]
I did the following:

1. npm i -S react-native-unified-contacts
2. In Xcode -> Add Files to "MyProject" 
3. Selected folder node_modules/react-native-unified-contacts/RNUnifiedContacts
4. Added var Contacts = require('react-native-unified-contacts'); to my project.
5. Clean / Rebuilt project in Xcode
6. Contacts is undefined.

I will try to remove my node_modules and perform an npm install. Sometimes that fixes things. Here's what my project structure looks like after adding RNUnifiedContacts.

![screen shot 2016-06-22 at 4 17 20 pm](https://cloud.githubusercontent.com/assets/251495/16282169/92137c00-3895-11e6-8dce-674e832e090a.png)

**Comment by joshuapinter** [comment]
Hmm... that should be all that you need to do. 

Also try to start the RN server with `npm start -- --reset-cache`. That sometimes helps.

**Comment by antonellil** [comment]
I am having the same issue, Contacts is showing up as undefined. Does an explicit library reference need to be added or something?

**Comment by antonellil** [comment]
Solution - The RNUnifiedContacts folder needs to be added under the core Project folder (in RgoVindji's case the Bunch folder)

**Comment by joshuapinter** [comment]
@antonellil Interesting, I don't have mine added there. It's just at the project root. But, you're saying doing that worked for you?

**Comment by antonellil** [comment]
Yes that worked for me

**Comment by joshuapinter** [comment]
@antonellil Okay, great. Thanks for sharing.

**Comment by iraycd** [comment]
I get `undefined is not an object (evaluating Contacts.getContacts)`

**Comment by joshuapinter** [comment]
@iraycd What does your import statement look like? And what does your XCode project structure look like?

**Comment by iraycd** [comment]
```
import React, { Component } from 'react';
import NavigationBar from 'react-native-navbar';

import {
    StyleSheet,
    Text,
    View
} from 'react-native';
var Contacts  = require('react-native-unified-contacts');
Contacts.getContacts( (error, contacts) =>  {
  if (error) {
    console.error(error);
  }
  else {
    console.log(contacts);
  }
});
```

<img width="250" alt="screen shot 2016-09-08 at 10 35 01 pm" src="https://cloud.githubusercontent.com/assets/1450984/18358804/8c9433f2-7614-11e6-946c-2b2891067d7b.png">

**Comment by joshuapinter** [comment]
Can you try dragging `RNUnifiedContacts` to be "under" the "top-level" `DoGroups`. For example, this is how I have it in my Project for ntwrk: 

![screenshot 2016-09-08 11 14 15](https://cloud.githubusercontent.com/assets/180819/18359104/96086a66-75b5-11e6-9618-294a062fcaa8.png)

**Comment by joshuapinter** [comment]
Also, make sure you restart the npm server.

**Comment by iraycd** [comment]
So, the error was more of Swift error and iOS 9.0 Error.
So, sent a new pull request.
