### ISSUE TITLE
[Android] Pointer issue

### ISSUE THREAD

**Issue by paintedbicycle** [joshuapinter/react-native-unified-contacts#70]
Hey,

When I use the exampleApp everything works fine, so it's definitely something I'm doing. Additionally, my iOS app is also working fine - but I'm having some trouble with my android app. My app loads but crashes when I interact with it.

Does the below stack trace point you in any direction? I'm not strong with Java and so have been struggling with this and getting nowhere.

<img width="963" alt="screen shot 2018-05-10 at 1 10 58 pm" src="https://user-images.githubusercontent.com/371114/39883138-3e47d83c-5486-11e8-8f31-2dcb94d64ca1.png">

**Comment by joshuapinter** [comment]
Hmm, is this on `master`? Did this just start happening after a fresh pull from `master`?

What ReactNativeUnifiedContacts commands are you calling from your app? Have you isolated the problematic method?

I'll know move from the above questions, but also check the following in your MainActivity: 

1. Make sure your MainActivity `implements ActivityCompat.OnRequestPermissionsResultCallback`. It should look something like this: 

```java
public class MainActivity extends ReactActivity implements ActivityCompat.OnRequestPermissionsResultCallback {
```

2. Add the following override method:

```java
@Override
public void onRequestPermissionsResult(int requestCode, String permissions[], int[] grantResults) {

  RNUnifiedContactsPackage.onRequestPermissionsResult( requestCode, permissions, grantResults );

}
```

**Comment by paintedbicycle** [comment]
I added the lines you mention above, but it didn't solve the problem. Same error.

<img width="967" alt="screen shot 2018-05-10 at 8 00 16 pm" src="https://user-images.githubusercontent.com/371114/39885430-e0d4f138-548c-11e8-8c47-a3898789d3bf.png">

The issue isn't new to this new build, no. Yes I'm currently using master.

**Comment by joshuapinter** [comment]
That looks like a different error, no?

**Comment by joshuapinter** [comment]
Do you know what line of _your_ code triggers this error?

**Comment by joshuapinter** [comment]
Ugh, I know that feeling. Super frustrating!

Are you using `selectContact` at all?

**Comment by joshuapinter** [comment]
I properly added/fixed the `selectContact` in Android, which might fix your issue. It's in master so give it a try and let me know how it goes.

This marks the first method in Android that _isn't_ available in iOS. Whoop! 😜

**Comment by paintedbicycle** [comment]
No, I wasn't using it. But we can close this until I learn more. 

I am using alreadyRequestedAccessToContacts though. I commented it out, but would be good to get it added to finalize the permissions on Android. I believe Android has the same states as iOS - I think there is an UNDEFINED state we can check for. I couldn't quite get my patch to work but let me know if you find out a good way to do it.

**Comment by joshuapinter** [comment]
Dang. I'm going to re-open this and if I can get you to track down the line of your code that is causing the error in Android, that would be great. I don't want to ignore this as other people might run into, too, so I'd like a paper trail of a solution.

**Comment by paintedbicycle** [comment]
Could it be anything about installation? It was working totally fine for me, but I have changed quite a few things in my app.

The reason I ask is that my app opens fine but when I interact with my app (in my case taking a photo), the photo gets taken, but then my app crashes. There is no use of contacts here and contacts aren't even called in that component. So it seems very, very strange. And remember that everything is totally fine in iOS, no issues.

**Comment by joshuapinter** [comment]
Kay, I think I know what the issue is related to.

With Android, they use `onActivityResult` to handle situations where you're asking the user or the operating system to do something and then return something afterwards. 

For example, this happens in `selectContact` when we launch and `Intent` to open the Contacts app and allow the user to select a Contact. After they select a Contact, it returns the details to a method called `onActivityResult`.

This also happens when taking a photo. It creates an `Intent` to open up the camera app and when the photo is taken (and accepted) it returns it to the `onActivityResult`.

Because React Native is kind of a special beast, there might be a collision of the library you're using for capturing photos (e.g. `react-native-camera`) and the Unified Contacts.

Until we can diagnose this a bit more, I'm going to disable the `selectContact` in Android, push that to `master` and I want you to try that to see if it works. 

Sound good?

**Comment by paintedbicycle** [comment]
Very interesting. Ok, sure. Keep in mind I'm not using select contact. It's been an issue for me for about a month now. But I'm definitely willing to keep trying to get this working this weekend!

**Comment by joshuapinter** [comment]
If there's a collision with `onActivityResult` then it would happen even without using `selectContact` because the methods are still defined. 

The reason the ExampleApp would still work fine is because there are no other react native libraries being included.

What camera library are you using?

**Comment by paintedbicycle** [comment]
Ok exciting. This has been a very difficult bug for me that has basically meant I've stopped work on Android version.

I'm using React Native Image Crop Picker: https://github.com/ivpusic/react-native-image-crop-picker

**Comment by joshuapinter** [comment]
I wish I knew about this earlier, we could have fixed it up! :)

Okay, pushed a new commit to master that disables `selectContact` and the use of `onActivityResult`.

I'm not sure if this will resolve the issue you're seeing but it should.

If you can use the fresh version from master in your app and test it out on Android, that would be great!

**Comment by joshuapinter** [comment]
Sounds good! Have a great night.

**Comment by joshuapinter** [comment]
![celebrate](https://user-images.githubusercontent.com/180819/39937002-a764db8c-550b-11e8-926e-6c5f2a76474d.gif)

**Comment by paintedbicycle** [comment]
We're good. Thanks!

**Comment by joshuapinter** [comment]
👍
