### ISSUE TITLE
Releasing Android

### ISSUE THREAD

**Issue by chrisyeoward** [joshuapinter/react-native-unified-contacts#75]
Hi, 

Unsure if this has been covered elsewhere, but there's no Android source in the latest NPM release.

Would you be able to push out a new release, or is Android still waiting on specific fixes?

Thanks,

**Comment by paintedbicycle** [comment]
Hey @chrisyeoward - the Android code isn't _tagged_ to a specific version, but if you use the code in `master`, you'll get the Android functionality just fine. Keep in mind the compatibility table shown in the Readme - not all methods are available in Android.

There are a few ways to call `master` from npm but my package.json has this: 
` "react-native-unified-contacts": "https://github.com/joshuapinter/react-native-unified-contacts.git"
`

Paul

**Comment by jimmythompson** [comment]
Cheers for the quick reply. 😄

For context: I work with @chrisyeoward.

While we can definitely use Github for the time being, it'll probably be annoying - for us and yourselves - if we started depending on the master branch of your repo.

Are you planning on publishing new versions of this library to NPM in future? Is there anything we can help with?

**Comment by joshuapinter** [comment]
I agree. I think once we fix #74 and #52 we can release a new minor release to npm since there are no breaking changes.

We'll leave the 2.0.0 release for full Android support and Promises, which will introduce breaking changes.

**Comment by ibrahimab** [comment]
Any way you need help with #52  ? Something you are stuck on? Would love to upgrade to a android supported version.

**Comment by joshuapinter** [comment]
@ibrahimab That would be great. If you read Issue #52, you'll see that we're looking for a way to interpret single line addresses. If you can give @paintedbicycle a hand with that, that would help a lot.

**Comment by paintedbicycle** [comment]
There's now an `npm pre-release` that you can use to try out the Android version.

https://www.npmjs.com/package/react-native-unified-contacts/v/2.0.0-pre.1
