### ISSUE TITLE
How to get only updated contacts from the ANDROID side

### ISSUE THREAD

**Issue by Tracklous** [joshuapinter/react-native-unified-contacts#85]
Hello All,

My concern is regarding getAll function while fetching contacts from an Android device. I'm getting all contacts whenever I call for the contacts but that's a very heavy operation as far as I know. 

I'm looking for a way where I can get only updated contacts so that I can process only that chunk of data. Please revert as soon as possible.

**Comment by joshuapinter** [comment]
What’s an “updated Contact”?

**Comment by Tracklous** [comment]
is there any function in this library which will give us callback or some flag where we get to know that some contacts are deleted from the phone.

**Comment by joshuapinter** [comment]
After deleting the Contacts? I'm confused what you're asking about.

**Comment by Tracklous** [comment]
@joshuapinter Look initially, We get all contacts! Right.
 -----> Just suppose we got [Ankit, Joshuapinter, Tracklous, Joshua, Peter, Jack, Sam]
But later few of them deleted from the device. [Ankit, Joshua] --- removed 
-----> So this time we'll get [Joshuapinter, Tracklous,  Peter, Jack, Sam]


But I'm asking, is there any way by that I can get the list of the deleted item instead of the remaining. item.
expected ---> [Ankit, Joshua]

**Comment by joshuapinter** [comment]
Does Android provide a flag for deleted items? Wouldn't they just be deleted from the device?

You'll have to do some research and find out for yourself. When you do find out, post a reply back here to help myself and others if they ever need something like this.
