### ISSUE TITLE
Awesome work!

### ISSUE THREAD

**Issue by basdvries** [joshuapinter/react-native-unified-contacts#9]
Making an issue to thank you since there's no other way to do that. :')
Thanks for building the best contacts framework out there! When Android is supported as well, we'll definitely make the switch.

**Comment by joshuapinter** [comment]
@basdvries Dude, you just made my morning! 😊 

And, get ready for Android support because it's coming up quick. I built this library for my side project, **[ntwrk](ntwrkapp.com)**, which I just released for iOS and will be releasing for Android shortly.

**Comment by joshuapinter** [comment]
@basdvries Hey Bas! Just letting you know that Android support is up and running and could use a hand to test it out if you have a few minutes. Let me know.
