### ISSUE TITLE
No android folder when installing 1.6.2?

### ISSUE THREAD

**Issue by DaRizat** [joshuapinter/react-native-unified-contacts#90]
When installing 1.6.2 from npm or yarn, the android folder is not present in the package folder, which makes linking impossible. 

Workaround for now is cloning repo and copying android folder into the node_modules folder or cloning and linking the repo.

**Comment by brascene** [comment]
Why is this issue closed, it's still present like this, in my project that android folder is also missing..

**Comment by paintedbicycle** [comment]
@joshuapinter It might make sense to tag the current bleeding edge as an alpha release so people can at least try out the Android version using npm if they wanted to? I don't think many people know how to request the bleeding edge commits from a Git repo from their `package.json` and it's not that convenient to do so anyway

**Comment by joshuapinter** [comment]
Probably a good idea. You able to do that with your permissions?

**Comment by paintedbicycle** [comment]
I'll find out!

**Comment by paintedbicycle** [comment]
Ok I've pushed a tagged `alpha release` to Github (https://github.com/joshuapinter/react-native-unified-contacts/releases/tag/v2.0.0-alpha-1), as the `npm` account owner I believe you'll need to publish this tag as a `beta release` over there:

https://medium.com/@kevinkreuzer/publishing-a-beta-or-alpha-version-to-npm-46035b630dd7

**Comment by joshuapinter** [comment]
Done. Published to npm as `2.0.0-pre.1`: 

https://www.npmjs.com/package/react-native-unified-contacts/v/2.0.0-pre.1

**Comment by paintedbicycle** [comment]
Beauty. 

@DaRizat @brascene - you're good to go
