### ISSUE TITLE
iOS 13 Support

### ISSUE THREAD

**Issue by elliotfleming** [joshuapinter/react-native-unified-contacts#95]
Hey, just a heads up - this package fails with the error `cnerrordomain 102` in iOS 13 since it tries to access the `note` field, which now requires a special entitlement `com.apple.developer.contacts.notes` that's only available by [submitting an application](https://developer.apple.com/contact/request/contact-note-field).

My fix was to simply comment out the two refererences to `note` in `RNUnifiedContacts.swift`.

```swift
...
// CNContactNoteKey
...
// addString(&contact, key: "note", value: cNContact.note)
...
```

**Comment by joshuapinter** [comment]
Interesting. So there's no way to obtain the notes without individually submitting an application to Apple?

**Comment by elliotfleming** [comment]
Their stance is that notes are a privacy issue since users put sensitive info there, so they're locking it down going forward. From what I can gather the people who've submitted applications haven't even been given a response. It could be one of those things where they're only going to allow the biggest players to play, but that's just speculation on my part.

**Comment by joshuapinter** [comment]
Thanks for the additional info. I'm going to release a new major version since this will break existing apps using this library that are trying to access the `.notes` attribute.

Then in a future version we can add an option to include it if the app using this library has request specific permission / entitlement for it.

Thanks!

**Comment by joshuapinter** [comment]
This has been merged into master and released to npm as v2.0.0-pre.2. Update your `package.json` accordingly or use `master` branch.

NOTE: You will no longer be able to access the `note` attribute of a Contact so update your app if you're doing that.

**Comment by divyanshu013** [comment]
Hi @joshuapinter, are there any other breaking changes in `v2.0.0-pre.2`? I checked the release description but it didn't say anything. Just wanted to confirm. Thanks.

**Comment by joshuapinter** [comment]
Not sure at this point. I have fallen short on developing this and keeping up with the CHANGELOG. I'm hoping to change that during this self-isolation period.

**Comment by divyanshu013** [comment]
I upgraded and haven't noticed any issues on iOS till now 😄

**Comment by joshuapinter** [comment]
🤞 :)
